import os

from .NDIlib import *
from .NDIlib.FourCCAudioType import FOURCC_AUDIO_TYPE_FLTP, FOURCC_AUDIO_TYPE_MAX
from .NDIlib.FourCCVideoType import (
    FOURCC_VIDEO_TYPE_BGRA,
    FOURCC_VIDEO_TYPE_BGRX,
    FOURCC_VIDEO_TYPE_I420,
    FOURCC_VIDEO_TYPE_MAX,
    FOURCC_VIDEO_TYPE_NV12,
    FOURCC_VIDEO_TYPE_P216,
    FOURCC_VIDEO_TYPE_PA16,
    FOURCC_VIDEO_TYPE_RGBA,
    FOURCC_VIDEO_TYPE_RGBX,
    FOURCC_VIDEO_TYPE_UYVA,
    FOURCC_VIDEO_TYPE_UYVY,
    FOURCC_VIDEO_TYPE_YV12,
)
from .NDIlib.FrameFormatType import (
    FRAME_FORMAT_TYPE_FIELD_0,
    FRAME_FORMAT_TYPE_FIELD_1,
    FRAME_FORMAT_TYPE_INTERLEAVED,
    FRAME_FORMAT_TYPE_MAX,
    FRAME_FORMAT_TYPE_PROGRESSIVE,
)
from .NDIlib.FrameType import (
    FRAME_TYPE_AUDIO,
    FRAME_TYPE_ERROR,
    FRAME_TYPE_MAX,
    FRAME_TYPE_METADATA,
    FRAME_TYPE_NONE,
    FRAME_TYPE_STATUS_CHANGE,
    FRAME_TYPE_VIDEO,
)
from .NDIlib.RecvBandwidth import (
    RECV_BANDWIDTH_AUDIO_ONLY,
    RECV_BANDWIDTH_HIGHEST,
    RECV_BANDWIDTH_LOWEST,
    RECV_BANDWIDTH_MAX,
    RECV_BANDWIDTH_METADATA_ONLY,
)
from .NDIlib.RecvColorFormat import (
    RECV_COLOR_FORMAT_BEST,
    RECV_COLOR_FORMAT_BGRX_BGRA,
    RECV_COLOR_FORMAT_E_BGRX_BGRA,
    RECV_COLOR_FORMAT_E_RGBX_RGBA,
    RECV_COLOR_FORMAT_E_UYVY_BGRA,
    RECV_COLOR_FORMAT_E_UYVY_RGBA,
    RECV_COLOR_FORMAT_FASTEST,
    RECV_COLOR_FORMAT_MAX,
    RECV_COLOR_FORMAT_RGBX_RGBA,
    RECV_COLOR_FORMAT_UYVY_BGRA,
    RECV_COLOR_FORMAT_UYVY_RGBA,
)

if os.name == "nt" and sys.version_info.major >= 3 and sys.version_info.minor >= 8:
    from .NDIlib.RecvColorFormat import RECV_COLOR_FORMAT_BGRX_BGRA_FLIPPED

__all__ = [
    "FRAME_TYPE_NONE",
    "FRAME_TYPE_VIDEO",
    "FRAME_TYPE_AUDIO",
    "FRAME_TYPE_METADATA",
    "FRAME_TYPE_STATUS_CHANGE",
    "FRAME_TYPE_ERROR",
    "FRAME_TYPE_MAX",
    "FRAME_FORMAT_TYPE_PROGRESSIVE",
    "FRAME_FORMAT_TYPE_INTERLEAVED",
    "FRAME_FORMAT_TYPE_FIELD_0",
    "FRAME_FORMAT_TYPE_FIELD_1",
    "FRAME_FORMAT_TYPE_MAX",
    "RECV_BANDWIDTH_LOWEST",
    "RECV_BANDWIDTH_HIGHEST",
    "RECV_BANDWIDTH_METADATA_ONLY",
    "RECV_BANDWIDTH_AUDIO_ONLY",
    "RECV_BANDWIDTH_MAX",
    "RECV_COLOR_FORMAT_FASTEST",
    "RECV_COLOR_FORMAT_BEST",
    "RECV_COLOR_FORMAT_MAX",
    "RECV_COLOR_FORMAT_BGRX_BGRA",
    "RECV_COLOR_FORMAT_RGBX_RGBA",
    "RECV_COLOR_FORMAT_UYVY_BGRA",
    "RECV_COLOR_FORMAT_UYVY_RGBA",
    "RECV_COLOR_FORMAT_E_BGRX_BGRA",
    "RECV_COLOR_FORMAT_E_RGBX_RGBA",
    "RECV_COLOR_FORMAT_E_UYVY_BGRA",
    "RECV_COLOR_FORMAT_E_UYVY_RGBA",
    "FOURCC_VIDEO_TYPE_BGRX",
    "FOURCC_VIDEO_TYPE_BGRA",
    "FOURCC_VIDEO_TYPE_RGBX",
    "FOURCC_VIDEO_TYPE_RGBA",
    "FOURCC_VIDEO_TYPE_UYVY",
    "FOURCC_VIDEO_TYPE_UYVA",
    "FOURCC_VIDEO_TYPE_I420",
    "FOURCC_VIDEO_TYPE_YV12",
    "FOURCC_VIDEO_TYPE_NV12",
    "FOURCC_VIDEO_TYPE_P216",
    "FOURCC_VIDEO_TYPE_PA16",
    "FOURCC_VIDEO_TYPE_MAX",
    "FOURCC_AUDIO_TYPE_FLTP",
    "FOURCC_AUDIO_TYPE_MAX",
]
